id = "monokai like"
name = "monokai like"
version = "0.0.1"
schema_version = 1
description = "monokai classic theme for Zed"
repository = "https://github.com/fardin3693/monokai-theme-for-ZED"
authors = ["monokai team, bring to Zed by Fardin"]
themes = ["themes/one-dark-pro-max.json"]
icon_themes = []
languages = []

[lib]

[grammars]

[language_servers]

[context_servers]

[slash_commands]

[indexed_docs_providers]
