id = "one-dark-pro-max"
name = "One Dark Pro Max"
version = "0.0.1"
schema_version = 1
description = "One Dark Pro Max theme for Zed :)"
repository = "https://github.com/kussumma/one-dark-pro-max"
authors = ["Kusuma"]
themes = ["themes/one-dark-pro-max.json"]
icon_themes = []
languages = []

[lib]

[grammars]

[language_servers]

[context_servers]

[slash_commands]

[indexed_docs_providers]
